# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-portal:
    build:
      target: development
    image: ffc-tcg-portal-development
    container_name: ffc-tcg-portal-development
    ports:
      - "3054:3054"
      - "9254:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
