services:
  ffc-tcg-portal:
    build:
      context: .
      target: production
    image: ffc-tcg-portal
    container_name: ffc-tcg-portal
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-portal-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      ENVIRONMENT_CODE: ${ENVIRONMENT_CODE:-local}
      DEFRA_ID_ENABLED: ${DEFRA_ID_ENABLED:-false}
      DEFRA_ID_WELL_KNOWN_URL: ${DEFRA_ID_WELL_KNOWN_URL}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY}
      DEFRA_ID_REDIRECT_URL: ${DEFRA_ID_REDIRECT_URL:-http://localhost:3000/sign-in-oidc}
      DEV_AUTH_PRIVATE_KEY: ${DEV_AUTH_PRIVATE_KEY}
      DEV_AUTH_PUBLIC_KEY: ${DEV_AUTH_PUBLIC_KEY}
      ABACO_ENDPOINT: ${ABACO_ENDPOINT:-http://ffc-tcg-abaco-agri-stub:3052}
      SFI_APPLY_URL: http://localhost:3055
      BPS_APPLY_URL: http://localhost:3055
      CS_APPLY_URL: http://localhost:3055
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
