services:
  ffc-tcg-portal:
    build:
      context: .
      target: production
    image: ffc-tcg-portal
    container_name: ffc-tcg-portal
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-portal-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      ENVIRONMENT_CODE: ${ENVIRONMENT_CODE:-local}
