{{- include "ffc-helm-library.container-config-map" (list . "ffc-tcg-portal.config-map") -}}
{{- define "ffc-tcg-portal.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  DEFRA_ID_ENABLED: {{ quote .Values.container.defraIdEnabled }}
  DEFRA_ID_WELL_KNOWN_URL: {{ quote .Values.container.defraIdWellKnownUrl }}
  DEFRA_ID_CLIENT_ID: {{ quote .Values.container.defraIdClientId }}  
  DEFRA_ID_SERVICE_ID: {{ quote .Values.container.defraIdServiceId }}
  DEFRA_ID_POLICY: {{ quote .Values.container.defraIdPolicy }}
  {{- if .Values.pr }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/{{ .Values.container.defraIdRedirectUrl }}
  {{ else }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ .Values.container.defraIdRedirectUrl }}
  {{- end }}
  ENVIRONMENT_CODE: {{.Values.environmentCode}}
  {{- if not .Values.container.useAbacoStub }}
  {{- if and (.Values.environmentCode) (ne (.Values.environmentCode | toString ) "snd") }}
  ABACO_ENDPOINT: {{ .Values.container.abacoEndpoint }}-{{ .Values.environmentCode }}.{{ .Values.ingress.server }}
  {{ else }}
  ABACO_ENDPOINT: {{ .Values.container.abacoEndpoint }}.{{ .Values.ingress.server }}
  {{- end }}
  {{ else }}
  {{- if and (.Values.environmentCode) (ne (.Values.environmentCode | toString ) "snd") }}
  ABACO_ENDPOINT: {{ .Values.container.stubEndpoint }}.{{ .Values.workstream }}-{{ .Values.environmentCode }}
  {{ else }}
  ABACO_ENDPOINT: {{ .Values.container.stubEndpoint }}.{{ .Values.workstream }}
  {{- end }}
  {{- end }}

{{- end -}}
