{{- include "ffc-helm-library.container-secret" (list . "ffc-tcg-portal.container-secret") -}}
{{- define "ffc-tcg-portal.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  DEFRA_ID_CLIENT_SECRET: {{ quote .Values.defraIdClientSecret }}
{{- end -}}
