{{- include "ffc-helm-library.container-secret" (list . "ffc-tcg-portal.container-secret") -}}
{{- define "ffc-tcg-portal.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  DEFRA_ID_CLIENT_SECRET: {{ quote .Values.container.defraIdClientSecret }}
  {{- if .Values.container.devAuthPrivateKey }}
  DEV_AUTH_PRIVATE_KEY: {{ quote .Values.container.devAuthPrivateKey }}
  {{- end }}
  {{- if .Values.container.devAuthPublicKey }}
  DEV_AUTH_PUBLIC_KEY: {{ quote .Values.container.devAuthPublicKey }}
  {{- end }}
{{- end -}}
