environment: production
environmentCode:
name: ffc-tcg-portal
namespace: ffc-tcg
workstream: ffc-tcg
image: ffc-tcg-portal

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-portal-config-map

containerSecret:
  name: ffc-tcg-portal-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3054

livenessProbe:
  path: /healthz
  port: 3054
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3054
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-tcg-portal
  server: example.com

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID