environment: production
environmentCode:
name: ffc-tcg-portal
namespace: ffc-tcg
workstream: ffc-tcg
image: ffc-tcg-portal

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-portal-config-map

containerSecret:
  name: ffc-tcg-portal-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 200Mi
  requestCpu: 200m
  limitMemory: 200Mi
  limitCpu: 200m
  port: 3000
  defraIdEnabled: true
  defraIdWellKnownUrl: not-a-real-url
  defraIdClientId: not-a-real-clientID
  defraIdClientSecret: not-a-real-clientSecret
  defraIdServiceId: not-a-real-serviceID
  defraIdPolicy: not-a-real-policy
  defraIdRedirectUrl: sign-in-oidc
  abacoEndpoint: https://ffc-iacs-agri
  useAbacoStub: false
  stubEndpoint: http://ffc-tcg-abaco-agri-stub

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-tcg-portal
  server: example.com

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
